Ext.define('VMS.model.InnerCarRecord',{
	extend:'Ext.data.Model',
	fields:[
	        {name:'type',type:'varchar'},
	        {name:'date',type:'date'},
	        {name:'car.license',type:'varchar'},
	        {name:'car.user.realname',type:'varchar'},
	        {name:'status',type:'varchar'}
	        ]
});